name: nasqar_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base==4.2.3 
  - r-shiny
  - r-dt
  - r-shinydashboard
  - r-shinyjs
  - r-shinyBS
  - r-shinycssloaders
  - r-uuid
  - r-plotly
  - r-markdown 
  - r-devtools  
  - r-shinycssloaders
  - r-devtools
  - r-ggupset
  - r-ggridges
  - r-europepmc
  - r-rhandsontable
  - r-readr
  - r-rcolorbrewer
  - r-heatmaply
  - r-ggthemes
  - r-igraph
  - r-sodium
  - r-nmf
  - r-rclipboard
  - r-vennDiagram
  - r-pheatmap
  - r-gplots
  - r-ggvis
  - umap-learn  
  - ucsc-cell-browser
  - libsodium

